// Cross-platform helpers for writing generated bytes to a usable URI, sharing
// files, and saving images to the device gallery. Native uses expo-file-system
// (cache dir) + expo-sharing/expo-media-library; web falls back to data URIs
// and a synthetic <a download> click.
import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system';
import { fromByteArray } from 'base64-js';
// @ts-ignore - upng-js has no types
import UPNG from 'upng-js';

function base64ToDataUri(base64: string, mime: string) {
  return `data:${mime};base64,${base64}`;
}

/** Encodes an RGBA buffer as a PNG and returns a URI usable as an <Image> source. */
export async function writePngFromRGBA(rgba: Uint8ClampedArray, width: number, height: number): Promise<string> {
  const pngBuffer: ArrayBuffer = UPNG.encode([rgba.buffer], width, height, 0);
  const base64 = fromByteArray(new Uint8Array(pngBuffer));
  return writeBase64Image(base64, 'png');
}

/** Persists a base64 payload to a file (native) or a data: URI (web) and returns the URI. */
export async function writeBase64Image(base64: string, ext: 'png' | 'jpg' | 'webp' = 'png'): Promise<string> {
  const mime = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
  if (Platform.OS === 'web') {
    return base64ToDataUri(base64, mime);
  }
  const dir = (FileSystem as any).cacheDirectory ?? (FileSystem as any).documentDirectory;
  const fileUri = `${dir}photo-tools-${Date.now()}-${Math.round(Math.random() * 1e6)}.${ext}`;
  await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: 'base64' as const });
  return fileUri;
}

/**
 * Convert an existing image URI to WEBP format.
 * On web, uses Canvas toDataURL('image/webp') — all modern browsers support it.
 * On native, uses expo-image-manipulator with SaveFormat.WEBP when available;
 * falls back to JPEG and labels the file .jpg so the extension always matches
 * the actual byte content.
 *
 * Returns { uri, ext } so callers can use the correct file extension.
 */
export async function convertToWebP(
  uri: string,
  quality = 0.88
): Promise<{ uri: string; ext: 'webp' | 'jpg' }> {
  if (Platform.OS === 'web') {
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const img = new window.Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d')!;
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/webp', quality));
      };
      img.onerror = () => reject(new Error('Failed to load image for WEBP conversion'));
      img.src = uri;
    });
    return { uri: dataUrl, ext: 'webp' };
  }

  // Native: check if WEBP SaveFormat is available (Expo SDK ≥ 49 on some platforms)
  const ImageManipulator = await import('expo-image-manipulator');
  const SaveFormat = (ImageManipulator as any).SaveFormat;
  const hasWebP = Boolean(SaveFormat?.WEBP);
  const format = hasWebP ? SaveFormat.WEBP : (SaveFormat?.JPEG ?? 'jpeg');
  const ext: 'webp' | 'jpg' = hasWebP ? 'webp' : 'jpg';

  const result = await (ImageManipulator as any).manipulateAsync(uri, [], {
    compress: quality,
    format,
  });
  const dir = (FileSystem as any).cacheDirectory ?? (FileSystem as any).documentDirectory;
  const dest = `${dir}photo-${ext}-${Date.now()}.${ext}`;
  await FileSystem.copyAsync({ from: result.uri, to: dest });
  return { uri: dest, ext };
}

export function guessFileName(prefix: string, ext: string): string {
  return `${prefix}-${Date.now()}.${ext}`;
}

/** Downloads (web) or shares (native) a result file to the user. */
export async function exportFile(uri: string, fileName: string): Promise<void> {
  if (Platform.OS === 'web') {
    const a = document.createElement('a');
    a.href = uri;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    return;
  }
  const Sharing = await import('expo-sharing');
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    // Detect MIME type from file name extension
    const lower = fileName.toLowerCase();
    const mimeType =
      lower.endsWith('.png')  ? 'image/png'       :
      lower.endsWith('.webp') ? 'image/webp'       :
      lower.endsWith('.pdf')  ? 'application/pdf'  :
      lower.endsWith('.zip')  ? 'application/zip'  :
      'image/jpeg';
    await Sharing.shareAsync(uri, { mimeType });
  }
}

/** Saves an image result to the device's photo gallery (native only, no-op on web). */
export async function saveToGallery(uri: string): Promise<boolean> {
  if (Platform.OS === 'web') return false;
  const MediaLibrary = await import('expo-media-library');
  const { status } = await MediaLibrary.requestPermissionsAsync();
  if (status !== 'granted') return false;
  await MediaLibrary.saveToLibraryAsync(uri);
  return true;
}

export async function readFileSize(uri: string): Promise<number | undefined> {
  if (Platform.OS === 'web') {
    try {
      const res = await fetch(uri);
      const blob = await res.blob();
      return blob.size;
    } catch {
      return undefined;
    }
  }
  try {
    const info = await FileSystem.getInfoAsync(uri, { size: true } as any);
    return (info as any).size;
  } catch {
    return undefined;
  }
}
