// Cross-platform helpers for writing generated bytes to a usable URI, sharing
// files, and saving images to the device gallery. Native uses expo-file-system
// (cache dir) + expo-sharing/expo-media-library; web falls back to data URIs
// and a synthetic <a download> click.
import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system';
import { fromByteArray } from 'base64-js';
// @ts-ignore - upng-js has no types
import UPNG from 'upng-js';

function base64ToDataUri(base64: string, mime: string) {
  return `data:${mime};base64,${base64}`;
}

/** Encodes an RGBA buffer as a PNG and returns a URI usable as an <Image> source. */
export async function writePngFromRGBA(rgba: Uint8ClampedArray, width: number, height: number): Promise<string> {
  const pngBuffer: ArrayBuffer = UPNG.encode([rgba.buffer], width, height, 0);
  const base64 = fromByteArray(new Uint8Array(pngBuffer));
  return writeBase64Image(base64, 'png');
}

/** Persists a base64 payload to a file (native) or a data: URI (web) and returns the URI. */
export async function writeBase64Image(base64: string, ext: 'png' | 'jpg' = 'png'): Promise<string> {
  const mime = ext === 'png' ? 'image/png' : 'image/jpeg';
  if (Platform.OS === 'web') {
    return base64ToDataUri(base64, mime);
  }
  const dir = (FileSystem as any).cacheDirectory ?? (FileSystem as any).documentDirectory;
  const fileUri = `${dir}photo-tools-${Date.now()}-${Math.round(Math.random() * 1e6)}.${ext}`;
  await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: 'base64' as const });
  return fileUri;
}

export function guessFileName(prefix: string, ext: string): string {
  return `${prefix}-${Date.now()}.${ext}`;
}

/** Downloads (web) or shares (native) a result file to the user. */
export async function exportFile(uri: string, fileName: string): Promise<void> {
  if (Platform.OS === 'web') {
    const a = document.createElement('a');
    a.href = uri;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    return;
  }
  const Sharing = await import('expo-sharing');
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri);
  }
}

/** Saves an image result to the device's photo gallery (native only, no-op on web). */
export async function saveToGallery(uri: string): Promise<boolean> {
  if (Platform.OS === 'web') return false;
  const MediaLibrary = await import('expo-media-library');
  const { status } = await MediaLibrary.requestPermissionsAsync();
  if (status !== 'granted') return false;
  await MediaLibrary.saveToLibraryAsync(uri);
  return true;
}

export async function readFileSize(uri: string): Promise<number | undefined> {
  if (Platform.OS === 'web') {
    try {
      const res = await fetch(uri);
      const blob = await res.blob();
      return blob.size;
    } catch {
      return undefined;
    }
  }
  try {
    const info = await FileSystem.getInfoAsync(uri, { size: true } as any);
    return (info as any).size;
  } catch {
    return undefined;
  }
}
