// Single source of truth for the Photo Tools module: every tool's metadata and
// its route inside the app/photo-tools/* screen group. Consumed by AppContext
// (so the tool shows up in Dashboard / Tools / Favorites / Search like any
// other tool) and by the Photo Tools home screen itself.

export interface PhotoToolMeta {
  id: string;
  name: string;
  nameHi: string;
  iconName: string;
  color: string;
  description: string;
  descHi: string;
  route: string;
}

export const PHOTO_TOOLS: PhotoToolMeta[] = [
  {
    id: 'bg-remove',
    name: 'Background Remove',
    nameHi: 'बैकग्राउंड हटाएं',
    iconName: 'image-filter-none',
    color: '#10B981',
    description: 'Cut the subject out and swap or drop the background',
    descHi: 'विषय को काटें और बैकग्राउंड बदलें या हटाएं',
    route: '/photo-tools/background-remove',
  },
  {
    id: 'passport-photo',
    name: 'Passport Photo',
    nameHi: 'पासपोर्ट फोटो',
    iconName: 'card-account-details',
    color: '#3B82F6',
    description: 'Passport, visa & stamp size photos with print sheets',
    descHi: 'पासपोर्ट, वीजा और स्टैंप साइज़ फोटो प्रिंट शीट के साथ',
    route: '/photo-tools/passport-photo',
  },
  {
    id: 'image-resize',
    name: 'Photo Resize',
    nameHi: 'फोटो रीसाइज़',
    iconName: 'image-size-select-large',
    color: '#06B6D4',
    description: 'Resize to custom or preset dimensions',
    descHi: 'कस्टम या प्रीसेट आकार में बदलें',
    route: '/photo-tools/resize',
  },
  {
    id: 'photo-crop',
    name: 'Photo Crop',
    nameHi: 'फोटो क्रॉप',
    iconName: 'crop',
    color: '#0EA5E9',
    description: 'Free, square, portrait, landscape & custom crop',
    descHi: 'मुक्त, वर्गाकार, पोर्ट्रेट, लैंडस्केप और कस्टम क्रॉप',
    route: '/photo-tools/crop',
  },
  {
    id: 'photo-compress',
    name: 'Photo Compress',
    nameHi: 'फोटो कम्प्रेस',
    iconName: 'zip-box-outline',
    color: '#F59E0B',
    description: 'Shrink file size with an adjustable quality slider',
    descHi: 'क्वालिटी स्लाइडर से फाइल साइज़ कम करें',
    route: '/photo-tools/compress',
  },
  {
    id: 'photo-enhance',
    name: 'Photo Enhance',
    nameHi: 'फोटो एन्हांस',
    iconName: 'auto-fix',
    color: '#A855F7',
    description: 'Brightness, contrast, sharpness & saturation',
    descHi: 'ब्राइटनेस, कंट्रास्ट, शार्पनेस और सैचुरेशन',
    route: '/photo-tools/enhance',
  },
  {
    id: 'rotate-flip',
    name: 'Rotate & Flip',
    nameHi: 'घुमाएं और पलटें',
    iconName: 'rotate-right',
    color: '#22C55E',
    description: 'Rotate by 90°/180° or flip horizontally & vertically',
    descHi: '90°/180° घुमाएं या क्षैतिज/ऊर्ध्वाधर पलटें',
    route: '/photo-tools/rotate-flip',
  },
  {
    id: 'mirror-tool',
    name: 'Mirror Tool',
    nameHi: 'मिरर टूल',
    iconName: 'flip-horizontal',
    color: '#14B8A6',
    description: 'Mirror an image horizontally or vertically',
    descHi: 'इमेज को क्षैतिज या ऊर्ध्वाधर मिरर करें',
    route: '/photo-tools/mirror',
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    nameHi: 'इमेज कन्वर्टर',
    iconName: 'file-swap-outline',
    color: '#6366F1',
    description: 'Convert between PNG, JPG and WEBP',
    descHi: 'PNG, JPG और WEBP के बीच कन्वर्ट करें',
    route: '/photo-tools/converter',
  },
  {
    id: 'watermark-tool',
    name: 'Watermark Tool',
    nameHi: 'वॉटरमार्क टूल',
    iconName: 'water-outline',
    color: '#0891B2',
    description: 'Add a text or image watermark',
    descHi: 'टेक्स्ट या इमेज वॉटरमार्क जोड़ें',
    route: '/photo-tools/watermark',
  },
  {
    id: 'batch-resize',
    name: 'Batch Resize',
    nameHi: 'बैच रीसाइज़',
    iconName: 'image-multiple-outline',
    color: '#D97706',
    description: 'Resize many photos at once and download as a ZIP',
    descHi: 'एक साथ कई फोटो रीसाइज़ करें और ZIP डाउनलोड करें',
    route: '/photo-tools/batch-resize',
  },
  {
    id: 'face-center',
    name: 'Face Center Tool',
    nameHi: 'चेहरा केंद्र टूल',
    iconName: 'face-recognition',
    color: '#EC4899',
    description: 'Auto-detect and center a face, passport-ready',
    descHi: 'चेहरे को स्वतः पहचानें और पासपोर्ट के लिए केंद्र में रखें',
    route: '/photo-tools/face-center',
  },
  {
    id: 'white-background',
    name: 'White Background',
    nameHi: 'सफेद बैकग्राउंड',
    iconName: 'square-outline',
    color: '#64748B',
    description: 'Replace the background with pure white',
    descHi: 'बैकग्राउंड को शुद्ध सफेद से बदलें',
    route: '/photo-tools/white-background',
  },
  {
    id: 'blue-background',
    name: 'Blue Background',
    nameHi: 'नीला बैकग्राउंड',
    iconName: 'square',
    color: '#2563EB',
    description: 'Replace the background with passport blue',
    descHi: 'बैकग्राउंड को पासपोर्ट नीले रंग से बदलें',
    route: '/photo-tools/blue-background',
  },
  {
    id: 'red-background',
    name: 'Red Background',
    nameHi: 'लाल बैकग्राउंड',
    iconName: 'square',
    color: '#DC2626',
    description: 'Replace the background with red',
    descHi: 'बैकग्राउंड को लाल रंग से बदलें',
    route: '/photo-tools/red-background',
  },
  {
    id: 'transparent-png',
    name: 'Transparent PNG',
    nameHi: 'पारदर्शी PNG',
    iconName: 'checkerboard',
    color: '#059669',
    description: 'Remove background and save as transparent PNG',
    descHi: 'बैकग्राउंड हटाएं और पारदर्शी PNG सहेजें',
    route: '/photo-tools/transparent-png',
  },
  {
    id: 'metadata-viewer',
    name: 'Metadata Viewer',
    nameHi: 'मेटाडेटा व्यूअर',
    iconName: 'information-outline',
    color: '#6366F1',
    description: 'View EXIF data, camera info, GPS & file properties',
    descHi: 'EXIF डेटा, कैमरा जानकारी, GPS और फाइल प्रॉपर्टी देखें',
    route: '/photo-tools/metadata-viewer',
  },
  {
    id: 'duplicate-finder',
    name: 'Duplicate Finder',
    nameHi: 'डुप्लीकेट फाइंडर',
    iconName: 'content-duplicate',
    color: '#F43F5E',
    description: 'Find duplicate photos using hash-based comparison',
    descHi: 'हैश-आधारित तुलना से डुप्लीकेट फोटो खोजें',
    route: '/photo-tools/duplicate-finder',
  },
  {
    id: 'face-restore',
    name: 'Face Restore',
    nameHi: 'चेहरा पुनर्स्थापित',
    iconName: 'face-man-shimmer',
    color: '#8B5CF6',
    description: 'AI-powered restoration of blurry or old face photos',
    descHi: 'AI से धुंधले या पुराने चेहरे की फोटो साफ करें',
    route: '/photo-tools/face-restore',
  },
  {
    id: 'dpi-converter',
    name: 'DPI Converter',
    nameHi: 'DPI कन्वर्टर',
    iconName: 'printer',
    color: '#7C3AED',
    description: 'Convert image to 72, 150, 300 or 600 DPI for print',
    descHi: 'प्रिंट के लिए इमेज को 72, 150, 300 या 600 DPI में बदलें',
    route: '/photo-tools/dpi-converter',
  },
  {
    id: 'background-changer',
    name: 'Background Changer',
    nameHi: 'बैकग्राउंड बदलें',
    iconName: 'palette-outline',
    color: '#0D9488',
    description: 'Replace background with any color or preset',
    descHi: 'बैकग्राउंड को किसी भी रंग या प्रीसेट से बदलें',
    route: '/photo-tools/background-changer',
  },
  {
    id: 'blur-background',
    name: 'Blur Background',
    nameHi: 'बैकग्राउंड ब्लर',
    iconName: 'blur',
    color: '#6366F1',
    description: 'Keep subject sharp, blur the background (portrait mode)',
    descHi: 'विषय को शार्प रखें, बैकग्राउंड ब्लर करें (पोर्ट्रेट)',
    route: '/photo-tools/blur-background',
  },
  {
    id: 'color-correction',
    name: 'Color Correction',
    nameHi: 'रंग सुधार',
    iconName: 'palette',
    color: '#F97316',
    description: 'Gamma, white balance, shadows & highlights correction',
    descHi: 'गामा, व्हाइट बैलेंस, शैडो और हाइलाइट सुधार',
    route: '/photo-tools/color-correction',
  },
  {
    id: 'batch-rename',
    name: 'Batch Rename',
    nameHi: 'बैच रीनेम',
    iconName: 'rename-box',
    color: '#84CC16',
    description: 'Rename photos with prefix, suffix and auto-numbering',
    descHi: 'फोटो को प्रीफिक्स, सफिक्स और ऑटो-नंबरिंग से रीनेम करें',
    route: '/photo-tools/batch-rename',
  },
];

export function getPhotoTool(id: string): PhotoToolMeta | undefined {
  return PHOTO_TOOLS.find((t) => t.id === id);
}

export function getRouteForToolId(id: string): string | undefined {
  return getPhotoTool(id)?.route;
}
