// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/id-card/BoldCards.tsx": () => import("../components/mockups/id-card/BoldCards.tsx"),
  "./components/mockups/id-card/MinimalList.tsx": () => import("../components/mockups/id-card/MinimalList.tsx"),
  "./components/mockups/id-card/PremiumDark.tsx": () => import("../components/mockups/id-card/PremiumDark.tsx")
};
